### Variables globales
@baseUrl = http://localhost:3000
@token = tu_token
@credentialId = tu_uuid

### Registrar un nuevo usuario
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "email": "mauricio_test@ucb.edu.bo",
    "password": "MiPasswordSeguro123"
}

###

### Iniciar Sesión (Copia el token de la respuesta a la variable @token arriba)
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "mauricio_test@ucb.edu.bo",
    "password": "MiPasswordSeguro123"
}


### Crear una nueva credencial
# Requisito: POST /credentials
POST {{baseUrl}}/credentials
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "service_name": "Netflix",
    "account_username": "mauricio@ucb.edu.bo",
    "password": "SuperSecretNetflixPassword",
    "url": "https://netflix.com",
    "notes": "Cuenta familiar, perfil 2"
}

###

### Listar todas mis credenciales
# Requisito: GET /credentials
GET {{baseUrl}}/credentials
Authorization: Bearer {{token}}

###

### Obtener el detalle de una credencial específica (sin contraseña)
# Requisito: GET /credentials/{id}
GET {{baseUrl}}/credentials/{{credentialId}}
Authorization: Bearer {{token}}

###

### REVELAR CONTRASEÑA
# Requisito: Endpoint dedicado para ver contraseña y registrar auditoría
POST {{baseUrl}}/credentials/{{credentialId}}/reveal 
Authorization: Bearer {{token}}

###

### Actualizar una credencial (con o sin cambio de contraseña)
# Requisito: PUT/PATCH /credentials/{id} 
PUT {{baseUrl}}/credentials/{{credentialId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "service_name": "Netflix Familiar",
    "account_username": "mauricio_test@ucb.edu.bo",
    "password": "NuevoPasswordNetflix2026",
    "url": "https://netflix.com",
    "notes": "Actualicé la contraseña porque me robaron la cuenta"
}

###

### Eliminar una credencial
# Requisito: DELETE /credentials/{id}
DELETE {{baseUrl}}/credentials/{{credentialId}}
Authorization: Bearer {{token}}